
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: ${POSTGRES_USER:-username}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-111}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/latest/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d userdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data:

